Payment Formula Edited, Hints added for Formula, formatting Hints moved up above random number form
appdev-lessons/sinatra-omnicalc-1 pull request #1
Opened 2023-11-02 18:08 UTC by ananthprayaga

Hi @bpurinton ,

The changes in the Sinatra Omnicalc-1 include: 
1. A new image for the formula ( including all lowercase variable names) - Raghu had suggested a new name for the present value - I was thinking of "principal" but left it as is. 
2. Hints for the formula are paraphrased - added more explanation and grouped similar items.
3. Hints for the formatting are moved up above the random form (The random form now does look a bit weird coming after the formatting hint - please see attached screenshot
<img width="736" alt="Screen Shot 2023-11-02 at 1 06 51 PM" src="https://github.com/appdev-lessons/sinatra-omnicalc-1/assets/31409681/4d581684-1fb5-496a-88ca-82538a80532f">
)

2023-11-02 18:24 UTC, bpurinton commented on content.md
> +  a. Convert the user input from a string to a float.
Your a, b, c lists in the hints are not rendering on new lines in the rendered lesson. I suggest changing these to simple un-ordered lists without the lettering:

```
- Convert ...
- Divide ...
- etc.
```

2023-11-02 18:25 UTC, bpurinton commented on content.md
> +- The 'r' in the formula represents the interest rate per period. We take the APR(Annual Percentage Rate) as a string input, so follow these steps:
```suggestion
- The "r" in the formula represents the interest rate per period. We take the APR(Annual Percentage Rate) as a string input, so follow these steps:
```

Here and elsewhere use double quotes when referencing the formula parameters

2023-11-02 18:28 UTC, bpurinton commented on content.md
> +- If these are instance variables, you can access and view them within your program or view page.
```suggestion
- If these are instance variables (i.e. `@numerator` with the leading `@`), then you can access and view them within your `.erb` view templates.
```

2023-11-02 18:28 UTC, bpurinton commented on content.md
> +- The 'r' in the formula represents the interest rate per period. We take the APR(Annual Percentage Rate) as a string input, so follow these steps:
```suggestion
- The 'r' in the formula represents the interest rate per period. We take the APR (Annual Percentage Rate) as a string input, so follow these steps:
```

2023-11-02 18:31 UTC, bpurinton commented on content.md
```suggestion

<div class="bg-blue-100 py-1 px-5" markdown="1">

Use the `precision` option on the `to_fs` method to round your results. If you are confused by the usage, then please click the links above to read more about these methods.
</div>

```

2023-11-02 18:31 UTC, bpurinton commented on content.md
```suggestion

<div class="bg-blue-100 py-1 px-5" markdown="1">

Use the `precision` option on the `to_fs` method to round your results. If you are confused by the usage, then please click the links above to read more about these methods.
</div>

```

2023-11-02 18:39 UTC, bpurinton commented on content.md
>  An example of a valid form; in particular, notice the `id=""` and `for=""` attributes:
Cool feature of our special markdown in learn:

You can write

```
```erb{Line:(ColumnX-ColumnY)}
some code
```
```

To highlight specific lines and columns. Give it a try and view the results of your change in the rendered lesson (https://learn.firstdraft.com/lessons/232-sinatra-omnicalc-1). 

For instance, in the code block below I might write:

```
```erb{3:(12-26),7:(12-25)}
```

See how that highlights the `for=""` and `id=""`?

2023-11-02 18:41 UTC, bpurinton requested changes
Nice work so far. A few suggestions. When you are done with these, re-request me for review and we will continue to go back and forth until I "approve" the changes.

2023-11-02 18:44 UTC, bpurinton commented
> Hints for the formatting are moved up above the random form (The random form now does look a bit weird coming after the formatting hint - please see attached screenshot)

Ah, I missed this. Please put this bullet above the APR. Best to keep the "simple" hints for the other routes all grouped together and then one longer section on APR and hints on formatting those results.

2023-11-02 20:16 UTC, ananthprayaga commented on content.md
> +  {: .free_text_number #time_taken title="Time taken" points="1" answer="any" }
Yeah - this one is interesting since it autoformats on save even if I delete the space - should I disable and save?

2023-11-02 20:27 UTC, ananthprayaga commented on content.md
>  An example of a valid form; in particular, notice the `id=""` and `for=""` attributes:
Oh yeah - I just tried this - it's pretty cool!

2023-11-02 20:28 UTC, ananthprayaga commented on content.md
>  An example of a valid form; in particular, notice the `id=""` and `for=""` attributes:
I also did the same for other id and for tags as well

2023-11-02 20:30 UTC, ananthprayaga commented
> > Hints for the formatting are moved up above the random form (The random form now does look a bit weird coming after the formatting hint - please see attached screenshot)
> 
> Ah, I missed this. Please put this bullet above the APR. Best to keep the "simple" hints for the other routes all grouped together and then one longer section on APR and hints on formatting those results.

I changed it, but should we move the navigation in the target and maybe in the starter code to show the payment calculation as the last menu item? (Currently, it is random number form as the last form to be completed) - May be this too much thinking on my side it actually doesn't matter.

2023-11-02 20:31 UTC, ananthprayaga commented on content.md
> +  a. Convert the user input from a string to a float.
This is completed - I'm not sure if I should resolve the conversation or if it is better for the reviewer to resolve it.

2023-11-02 20:31 UTC, ananthprayaga commented on content.md
> +- The 'r' in the formula represents the interest rate per period. We take the APR(Annual Percentage Rate) as a string input, so follow these steps:
This is completed

2023-11-02 20:31 UTC, ananthprayaga commented on content.md
> +- If these are instance variables, you can access and view them within your program or view page.
This is completed

2023-11-02 20:31 UTC, ananthprayaga commented on content.md
This is completed

2023-11-02 20:35 UTC, ananthprayaga commented on content.md
> +  {: .free_text_number #time_taken title="Time taken" points="1" answer="any" }
Turned of auto-format and saved it. This is completed

2023-11-02 20:35 UTC, ananthprayaga commented on content.md
>  An example of a valid form; in particular, notice the `id=""` and `for=""` attributes:
This is completed

2023-11-02 20:54 UTC, bpurinton commented on content.md
> +  a. Convert the user input from a string to a float.
I will resolve them.

2023-11-02 20:58 UTC, bpurinton approved these changes
> I changed it, but should we move the navigation in the target and maybe in the starter code to show the payment calculation as the last menu item?

I don't think this is necessary. We can leave the ordering of things as they are.

Everything LGTM, feel free to "squash and merge" this PR to `main`, which will automatically update the lesson (double check to be sure: https://learn.firstdraft.com/lessons/100-sinatra-omnicalc-1)

2023-11-03 14:16 UTC, ananthprayaga commented
Double checked the content - Squashing and merging.

2023-11-03 14:19 UTC, merged

2023-11-03 14:20 UTC, ananthprayaga commented
Deleted branch as well.